// <auto-generated />
using IrishHousingEstate.DataAccessApi.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace IrishHousingEstate.ServiceApi.Migrations
{
    [DbContext(typeof(IrishHousingEstateDbContext))]
    partial class IrishHousingEstateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("IrishHousingEstate.ModelApp.Models.HouseData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AreaGroupEffect")
                        .HasColumnType("integer");

                    b.Property<string>("BerRating")
                        .HasColumnType("text");

                    b.Property<string>("County")
                        .HasColumnType("text");

                    b.Property<int>("CountyEffect")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfBedrooms")
                        .HasColumnType("integer");

                    b.Property<int>("PropertySizeEffect")
                        .HasColumnType("integer");

                    b.Property<int>("PropertySizeSquareMeters")
                        .HasColumnType("integer");

                    b.Property<string>("YearBuild")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HouseDataModel");
                });
#pragma warning restore 612, 618
        }
    }
}
